export const COPY = {
  fr: {
    start: 'Commencer l’évaluation',
    stop: 'Arrêter',
    speaking: 'L’agent parle…',
    processing: 'Traitement…',
    hints: {
      idle: 'Laissez-vous guider par notre agent',
      listening: 'Parlez naturellement, nous vous écoutons',
      speaking: 'L’agent vous répond…',
      processing: 'Nous analysons votre avis…',
    },
    thanksTitle: 'Merci pour votre aide !',
    thanksBody: 'Votre avis a été transmis aux équipes Eurotunnel.',
    scoreLabel: 'Note estimée',
    alertLabel: 'Alerte opérationnelle détectée',
    viewReport: 'Voir comment votre avis a été compris',
    hideReport: 'Masquer la fiche',
    reportTitle: 'Votre fiche de retour',
    reportIntro: 'Voici ce que nous avons retenu de votre échange.',
    summaryLabel: 'En résumé',
    themesLabel: 'Sujets abordés',
    strengthsLabel: 'Ce qui a bien fonctionné',
    weaknessesLabel: 'À améliorer',
    quotesLabel: 'Vos propos',
    alertPassenger:
      'Un signalement a été transmis aux équipes concernées.',
    emptySection: 'Rien de notable',
    emailTitle: 'Suivi de votre avis',
    emailPrompt:
      'Entrez votre e-mail pour avoir connaissance des suites données à vos retours.',
    emailPlaceholder: 'vous@email.com',
    emailSubmit: 'Recevoir les suites',
    emailOptional: 'Facultatif — aucun spam.',
    emailInvalid: 'Merci d’entrer une adresse e-mail valide.',
    emailThanks: 'Merci. Nous vous tiendrons informé des suites données à votre avis.',
    themeLabels: {
      embarquement: 'Embarquement',
      terminal: 'Terminal',
      personnel: 'Personnel',
      attente: 'Temps d’attente',
      navette: 'Navette',
      restauration: 'Restauration',
      accessibilite: 'Accessibilité',
      information: 'Information',
      autre: 'Autre',
    },
    micDenied:
      'Pour discuter avec Taupitunnel, nous avons besoin de l’accès à votre micro.',
    micInApp:
      'Ouvrez cette page dans Safari (iPhone) ou Chrome (Android), pas dans Instagram, LinkedIn ou Messenger.',
    micUnsupported:
      'Ce navigateur ne permet pas d’utiliser le micro. Ouvrez le site dans Safari ou Chrome.',
    vapiMissing:
      'Vapi n’est pas configuré. Ajoutez NEXT_PUBLIC_VAPI_KEY et NEXT_PUBLIC_VAPI_ASSISTANT_ID dans le fichier .env.',
    sr: {
      idle: 'Prêt à commencer',
      listening: 'L’agent écoute',
      speaking: 'L’agent parle',
      processing: 'Traitement de votre avis',
      summary: 'Merci, votre avis a été envoyé',
    },
  },
  en: {
    start: 'Start the evaluation',
    stop: 'Stop',
    speaking: 'The agent is speaking…',
    processing: 'Processing…',
    hints: {
      idle: 'Let our agent guide you',
      listening: 'Speak naturally, we are listening',
      speaking: 'The agent is responding…',
      processing: 'We are reviewing your feedback…',
    },
    thanksTitle: 'Thank you for your help!',
    thanksBody: 'Your feedback has been sent to the Eurotunnel teams.',
    scoreLabel: 'Estimated score',
    alertLabel: 'Operational alert detected',
    viewReport: 'See how your feedback was understood',
    hideReport: 'Hide the report',
    reportTitle: 'Your feedback report',
    reportIntro: 'Here is what we took from your conversation.',
    summaryLabel: 'In short',
    themesLabel: 'Topics covered',
    strengthsLabel: 'What went well',
    weaknessesLabel: 'To improve',
    quotesLabel: 'Your words',
    alertPassenger: 'A report has been sent to the relevant teams.',
    emptySection: 'Nothing notable',
    emailTitle: 'Follow-up on your feedback',
    emailPrompt:
      'Enter your email to hear about the follow-up given to your feedback.',
    emailPlaceholder: 'you@email.com',
    emailSubmit: 'Get updates',
    emailOptional: 'Optional — no spam.',
    emailInvalid: 'Please enter a valid email address.',
    emailThanks: 'Thank you. We will keep you informed of the follow-up on your feedback.',
    themeLabels: {
      embarquement: 'Boarding',
      terminal: 'Terminal',
      personnel: 'Staff',
      attente: 'Waiting time',
      navette: 'Shuttle',
      restauration: 'Food & drink',
      accessibilite: 'Accessibility',
      information: 'Information',
      autre: 'Other',
    },
    micDenied:
      'To talk with Taupitunnel, we need access to your microphone.',
    micInApp:
      'Open this page in Safari (iPhone) or Chrome (Android), not in Instagram, LinkedIn or Messenger.',
    micUnsupported:
      'This browser cannot use the microphone. Open the site in Safari or Chrome.',
    vapiMissing:
      'Vapi is not configured. Add NEXT_PUBLIC_VAPI_KEY and NEXT_PUBLIC_VAPI_ASSISTANT_ID to your .env file.',
    sr: {
      idle: 'Ready to start',
      listening: 'The agent is listening',
      speaking: 'The agent is speaking',
      processing: 'Processing your feedback',
      summary: 'Thank you, your feedback was sent',
    },
  },
}
